name: Continuous Integration Tests
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

#    - name: Checkout exercise feedback
#      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

# Install dependencies
    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pandas
        pip install sqlalchemy

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Run testcases
    - name: Run test.sh
      run: |
        ./project/test.sh